[project]
name = "terminator-toolset"
version = "0.9.5"
description = "Terminator: Dark Fate - Defiance Modding ToolSet"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["terminator_toolset*"]
